### ISSUE TITLE
Generate span instead of div element

### ISSUE THREAD

**Issue by Speuta** [chandlerprall/DatabindExtension#12]
`<div>` break the style, not `<span>`

**Comment by ultimate-tester** [comment]
I agree that sometimes the div element can break the page, but a span is also not a universal answer. Span is inline which means it cannot accept block elements.

For now, put the bind tags right before or after the closest block parent (e.g div) to minimize re-rendering and prevent the problem you describe.

**Comment by Speuta** [comment]
Yes, you're right.
Maybe adding a `data-nunjucks-binding="your_id"` on children should be better.

**Comment by ultimate-tester** [comment]
It took some time, but the latest release will take care of this. Instead of requiring a wrapper div, the code will now handle it smarter. If there's elements it will assign a data tag to these elements with the ID. If it's just a text, it will wrap this in a span and then assign the ID to that element. This completely drops the requirement for a DIV wrapper element. With that info, I'll close this issue. Feel free to create a new one if you're still having issues.
